### ISSUE TITLE
Add EVM compatibility to the AccountContext

### ISSUE THREAD

**Issue by ClementWalter** [the-candy-shop/starksheet-monorepo#46]
## Context

The [`AccountContext`](../blob/packages/starksheet-webapp/src/contexts/AccountContext.tsx) is responsible for providing the "chain loging" to the app. Currently, it uses directly all the starknet stack for connecting wallets and submitting tx. We need to update this to pop up Evm wallets connect on EVM chain.

## Tasks

**Comment by robinstraub** [comment]
I can work on this
